services:
  banking-service:
    image: servulo/banking-service:v1
    container_name: banking-service-container
    environment:
      - QUARKUS_CLIENT_HTTP=host.docker.internal
      - QUARKUS_CLIENT_HTTP_PORT=8181
      - QUARKUS_DATASOURCE_USERNAME=servulo
      - QUARKUS_DATASOURCE_PASSWORD=123456
      - QUARKUS_DATASOURCE_HOST=postgres-db-alura-banking-service
      - QUARKUS_DATASOURCE_PORT=5432
    ports:
      - 8080:8080
    depends_on:
      - postgres-db-alura-banking-service
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-compose
    ports:
      - "6000:3000"
    depends_on:
      - prometheus      

  postgres-db-alura-banking-service:
    image: 'postgres:14'
    container_name: postgres-db-alura-banking-service-container
    environment:
      - POSTGRES_USER=servulo
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=agencia
    ports:
      - '5433:5432'
    volumes:
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'

volumes:
  postgres_data:
    driver: local