services:
  postgres-db-alura-banking-service:
    image: 'postgres:14'
    container_name: postgres-db-alura-banking-service-container
    environment:
      - POSTGRES_USER=servulo
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=agencia
    ports:
      - '5433:5432'
    volumes:
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
